"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { supabaseBrowser } from "@/lib/supabase/browser";
import { Navbar, NavbarInner } from "@/app/components/ui/Navbar";
import Button from "@/app/components/ui/Button";

const DT_COMPLETION_TRIGGER =
  "Your assessment is complete. I am generating your Rooftop Access Report now.";

// ─── Types ────────────────────────────────────────────────────────────────────
type QAEntry = { question: string; answer: string };

type AssessmentData = {
  contractorName: string;
  companyName: string;
  accessType: "ladder-audit" | "ladder-recommendation" | "hatch-audit" | "stairs-audit" | "";
  completedAt: Date | null;
  qaLog: QAEntry[];
  flags: string[];
  isComplete: boolean;
};

type DisplayItem =
  | { type: "ai"; text: string; id: number }
  | { type: "user"; text: string; id: number };

type ApiMsg = { role: "user" | "assistant"; content: string };

// ─── PDF helpers ─────────────────────────────────────────────────────────────
function pdfSafe(text: string): string {
  return text.replace(/⚠️/g, "[!]").replace(/[^\x00-\x7E]/g, "").trim();
}

function triggerBlobDownload(blob: Blob, data: AssessmentData) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  const safeName =
    [data.contractorName, data.companyName]
      .filter(Boolean)
      .join("_")
      .replace(/\s+/g, "_") || "assessment";
  a.download = `Anchor_Rooftop_Assessment_${safeName}.pdf`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 10_000);
}

async function generatePdf(data: AssessmentData): Promise<Blob> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "letter" });

  const PW = doc.internal.pageSize.getWidth();
  const PH = doc.internal.pageSize.getHeight();
  const ML = 48;
  const MR = PW - 48;
  const CW = MR - ML;
  const FOOTER_Y = PH - 28;
  const PAGE_BOTTOM = PH - 56;

  const C_GREEN    = "#047835";
  const C_DARKGRAY = "#1A1A1A";
  const C_GRAY     = "#76777B";
  const C_RULE     = "#DDDDDD";

  let y = 52;

  function ensureSpace(h: number) {
    if (y + h > PAGE_BOTTOM) { doc.addPage(); y = 52; }
  }

  function hRule() {
    doc.setDrawColor(C_RULE); doc.setLineWidth(0.75);
    doc.line(ML, y, MR, y); y += 14;
  }

  function addFooters() {
    const total = doc.getNumberOfPages();
    for (let p = 1; p <= total; p++) {
      doc.setPage(p);
      doc.setFontSize(8); doc.setFont("helvetica", "normal"); doc.setTextColor(C_GRAY);
      doc.text("Generated by Anchor Products Sales Copilot | anchorp.com", ML, FOOTER_Y);
      doc.text(`Page ${p} of ${total}`, MR, FOOTER_Y, { align: "right" });
    }
  }

  function bodyText(raw: string, opts: { bold?: boolean; color?: string; size?: number; indent?: number } = {}) {
    const size = opts.size ?? 10;
    const color = opts.color ?? C_DARKGRAY;
    const indent = opts.indent ?? 0;
    doc.setFontSize(size); doc.setFont("helvetica", opts.bold ? "bold" : "normal"); doc.setTextColor(color);
    const lines = doc.splitTextToSize(pdfSafe(raw), CW - indent);
    ensureSpace(lines.length * 14);
    doc.text(lines, ML + indent, y); y += lines.length * 14;
  }

  function sectionTitle(title: string) {
    ensureSpace(30);
    doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.setTextColor(C_DARKGRAY);
    doc.text(pdfSafe(title), ML, y); y += 18;
  }

  // Header
  doc.setFontSize(22); doc.setFont("helvetica", "bold"); doc.setTextColor(C_GREEN);
  doc.text("ANCHOR PRODUCTS", ML, y); y += 30;

  doc.setFontSize(14); doc.setFont("helvetica", "normal"); doc.setTextColor(C_DARKGRAY);
  doc.text("Rooftop Access & Egress Assessment Report", ML, y); y += 22;
  hRule();

  const reportDate = data.completedAt ?? new Date();
  const dateStr =
    reportDate.toLocaleDateString("en-US", { month: "long", day: "2-digit", year: "numeric" }) +
    " at " +
    reportDate.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" });

  bodyText(`Report Date: ${dateStr}`, { color: C_GRAY }); y += 2;
  const contractorLine = [data.contractorName, data.companyName].filter(Boolean).join(" — ") || "N/A";
  bodyText(`Contractor: ${contractorLine}`); y += 2;
  const ACCESS_LABELS: Record<string, string> = {
    "ladder-audit": "Ladder Audit",
    "ladder-recommendation": "Ladder Recommendation",
    "hatch-audit": "Hatch Audit",
    "stairs-audit": "Stairs Audit",
  };
  const accessLabel = data.accessType ? (ACCESS_LABELS[data.accessType] ?? data.accessType) : "Not specified";
  bodyText(`Access Type Assessed: ${accessLabel}`); y += 10;
  hRule();

  if (data.flags.length > 0) {
    ensureSpace(40);
    sectionTitle("[!] Compliance Flags");
    for (const flag of data.flags) { bodyText(`• ${flag}`, { indent: 8 }); y += 4; }
    y += 8; hRule();
  }

  sectionTitle("Assessment Q&A");
  for (const entry of data.qaLog) {
    ensureSpace(42);
    bodyText(entry.question, { bold: true }); y += 3;
    bodyText(entry.answer, { color: C_GRAY }); y += 12;
  }
  y += 4; hRule();

  sectionTitle("Recommended Anchor Products");
  bodyText(
    "Based on your assessment, the following Anchor Products categories are recommended for your site. Visit anchorp.com for full product details and specifications.",
    { color: C_GRAY }
  ); y += 10;

  const categories = ["Safety", "Rooftop Accessories"];
  if (data.accessType === "ladder-audit" || data.accessType === "ladder-recommendation") categories.push("Communications");
  if (data.accessType === "stairs-audit") categories.push("MEP/HVAC");
  for (const cat of categories) { bodyText(`• ${cat}`, { indent: 8 }); y += 3; }

  const hasRoofingCompatFlag = data.flags.some((f) =>
    f.toLowerCase().includes("roofing manufacturer") || f.toLowerCase().includes("u-anchor")
  );
  if (data.accessType === "stairs-audit" && hasRoofingCompatFlag) {
    y += 6;
    bodyText(
      "★ U-Anchor™ by Anchor Products — the only compression-free rooftop attachment included in North American roof manufacturer warranties.",
      { bold: true, indent: 8 }
    ); y += 3;
  }

  addFooters();
  return doc.output("blob");
}

// ─── Page ─────────────────────────────────────────────────────────────────────
export default function RooftopPage() {
  const router = useRouter();
  const supabase = useMemo(() => supabaseBrowser(), []);

  const [profileName, setProfileName]       = useState("");
  const [profileCompany, setProfileCompany] = useState("");
  const [profilePhone, setProfilePhone]     = useState("");
  const [profileEmail, setProfileEmail]     = useState("");
  const [userId, setUserId]                 = useState<string | null>(null);
  const [booting, setBooting]               = useState(true);

  const [display, setDisplay]         = useState<DisplayItem[]>([]);
  const [apiMsgs, setApiMsgs]         = useState<ApiMsg[]>([]);
  const [options, setOptions]         = useState<string[]>([]);
  const [loading, setLoading]         = useState(false);
  const [assessment, setAssessment]   = useState<AssessmentData>({
    contractorName: "", companyName: "", accessType: "",
    completedAt: null, qaLog: [], flags: [], isComplete: false,
  });
  const [pdfGenerating, setPdfGenerating] = useState(false);
  const [pdfBlob, setPdfBlob]             = useState<Blob | null>(null);
  const [pdfError, setPdfError]           = useState<string | null>(null);

  const idRef   = useRef(0);
  const scrollRef = useRef<HTMLDivElement | null>(null);

  const nextId = () => ++idRef.current;

  // ── Boot: auth + profile ──────────────────────────────────────────────────
  useEffect(() => {
    let alive = true;
    (async () => {
      try {
        const { data: ud } = await supabase.auth.getUser();
        if (!alive) return;
        if (!ud.user) { router.replace("/"); return; }

        setUserId(ud.user.id);

        const meta = ud.user.user_metadata ?? {};
        let name = meta.full_name || "";
        let company = meta.company || "";

        const { data: prof } = await supabase
          .from("profiles")
          .select("full_name,company,phone,email")
          .eq("id", ud.user.id)
          .maybeSingle();

        if (!alive) return;
        if (prof?.full_name) name    = prof.full_name;
        if (prof?.company)   company = prof.company;

        setProfileName(name);
        setProfileCompany(company);
        setProfilePhone((prof as any)?.phone || "");
        setProfileEmail((prof as any)?.email || ud.user.email || "");
        setAssessment((prev) => ({ ...prev, contractorName: name, companyName: company }));
      } finally {
        if (alive) setBooting(false);
      }
    })();
    return () => { alive = false; };
  }, [supabase, router]);

  // ── Auto-start: fetch first question once boot is done ───────────────────
  useEffect(() => {
    if (booting) return;
    callApi([], profileName, profileCompany);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [booting]);

  // ── Auto-scroll ───────────────────────────────────────────────────────────
  useEffect(() => {
    scrollRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [display, options, loading]);

  // ── Auto-generate PDF when complete ──────────────────────────────────────
  useEffect(() => {
    if (!assessment.isComplete || pdfGenerating || pdfBlob || pdfError) return;
    (async () => {
      setPdfGenerating(true);
      try {
        const snap = assessment;
        const blob = await generatePdf(snap);
        triggerBlobDownload(blob, snap);
        setPdfBlob(blob);

        if (userId) {
          const { error: insertErr } = await supabase.from("assessment_reports").insert({
            user_id: userId,
            contractor_name: snap.contractorName || null,
            company_name: snap.companyName || null,
            access_type: snap.accessType || null,
            flags_count: snap.flags.length,
            file_url: null,
          });
          if (insertErr) console.error("assessment_reports insert failed:", insertErr.message);
        }
      } catch (e: any) {
        setPdfError(e?.message || "PDF generation failed.");
      } finally {
        setPdfGenerating(false);
      }
    })();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [assessment.isComplete]);

  // ── API call ──────────────────────────────────────────────────────────────
  async function callApi(msgs: ApiMsg[], name = profileName, company = profileCompany) {
    setLoading(true);
    setOptions([]);
    try {
      const res = await fetch("/api/rooftop", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          messages: msgs,
          contractorName: name || undefined,
          companyName: company || undefined,
        }),
      });

      if (res.status === 401) { router.replace("/"); return; }

      const data = await res.json();
      const message: string      = data?.message ?? "Something went wrong. Please try again.";
      const newOptions: string[] = Array.isArray(data?.options) ? data.options : [];
      const isComplete: boolean  = !!data?.isComplete;
      const apiAccessType: string | null = data?.accessType ?? null;

      const aiItem: DisplayItem = { type: "ai", text: message, id: nextId() };
      const aiMsg: ApiMsg = { role: "assistant", content: message };

      setDisplay((prev) => [...prev, aiItem]);
      setApiMsgs((prev) => [...prev, aiMsg]);
      setOptions(newOptions);

      setAssessment((prev) => {
        const updated = { ...prev };

        if (apiAccessType && !prev.accessType) {
          updated.accessType = apiAccessType as AssessmentData["accessType"];
        }

        const newFlags = message
          .split("\n")
          .filter((l) => l.includes("⚠️"))
          .map((l) => l.trim())
          .filter(Boolean);
        if (newFlags.length > 0) {
          const seen = new Set(prev.flags);
          const merged = [...prev.flags];
          for (const f of newFlags) if (!seen.has(f)) merged.push(f);
          updated.flags = merged;
        }

        if (isComplete) {
          updated.isComplete = true;
          updated.completedAt = new Date();
        }

        return updated;
      });
    } catch {
      const errItem: DisplayItem = { type: "ai", text: "Network error. Please try again.", id: nextId() };
      setDisplay((prev) => [...prev, errItem]);
      setOptions(["Try again"]);
    } finally {
      setLoading(false);
    }
  }

  // ── Button selection ──────────────────────────────────────────────────────
  const handleSelect = useCallback(
    (option: string) => {
      if (loading || assessment.isComplete) return;

      const userItem: DisplayItem = { type: "user", text: option, id: nextId() };
      const userMsg: ApiMsg = { role: "user", content: option };
      const nextApiMsgs = [...apiMsgs, userMsg];

      setDisplay((prev) => [...prev, userItem]);
      setApiMsgs(nextApiMsgs);
      setOptions([]);

      setAssessment((prev) => {
        const lastAi = display.filter((d) => d.type === "ai").slice(-1)[0];
        return lastAi
          ? { ...prev, qaLog: [...prev.qaLog, { question: lastAi.text, answer: option }] }
          : prev;
      });

      callApi(nextApiMsgs);
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [loading, assessment.isComplete, apiMsgs, display]
  );

  // ─── Render ────────────────────────────────────────────────────────────────
  if (booting) {
    return (
      <main className="ds-page flex min-h-dvh items-center justify-center">
        <div className="text-sm text-[var(--anchor-gray)]">Loading…</div>
      </main>
    );
  }

  const progressCount = display.filter((d) => d.type === "user").length;

  return (
    <main className="ds-page flex h-[100dvh] flex-col overflow-hidden bg-[var(--surface-page)]">
      <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>

      {/* ── Navbar ──────────────────────────────────────────────────────────── */}
      <Navbar>
        <NavbarInner>
          <div className="flex min-w-0 items-center gap-3">
            <img src="/anchorp.svg" alt="Anchor" className="ds-logo shrink-0" />
            <div className="min-w-0 leading-tight">
              <div className="flex items-center gap-2">
                <span className="truncate text-sm font-semibold tracking-wide text-white">
                  Rooftop Equipment Audit
                </span>
                <span
                  className="hidden sm:inline-flex"
                  style={{
                    alignItems: "center",
                    padding: "2px 10px",
                    borderRadius: "9999px",
                    fontSize: "11px",
                    fontWeight: 600,
                    color: "white",
                    backgroundColor: "#11500F",
                    whiteSpace: "nowrap",
                    flexShrink: 0,
                  }}
                >
                  OSHA Guide
                </span>
              </div>
              <div className="truncate text-[12px] text-white/80">
                {profileName ? `${profileName}${profileCompany ? ` · ${profileCompany}` : ""}` : "Safety Verification"}
              </div>
            </div>
          </div>
          <div className="flex shrink-0 items-center gap-2">
            {progressCount > 0 && (
              <span className="hidden text-xs text-white/70 sm:block">
                {progressCount} question{progressCount !== 1 ? "s" : ""} answered
              </span>
            )}
            <Link href="/dashboard">
              <Button variant="ghost" className="h-9 px-3 text-sm">Dashboard</Button>
            </Link>
          </div>
        </NavbarInner>
      </Navbar>

      {/* Green accent strip */}
      <div style={{ height: 3, background: "linear-gradient(90deg, #047835, #9CE2BB)", flexShrink: 0 }} />

      {/* ── Conversation + buttons ───────────────────────────────────────────── */}
      <div className="flex flex-1 min-h-0 flex-col overflow-hidden">
        <div className="mx-auto flex h-full w-full max-w-2xl flex-col px-4 py-4">

          {/* Scrollable message history */}
          <div className="flex-1 min-h-0 overflow-y-auto [scrollbar-width:thin] space-y-3 pb-4">

            {/* Profile card – same pattern as Project Identifier & Commission Claim */}
            {(profileName || profileEmail) && (
              <div className="rounded-2xl border border-black/10 bg-white px-4 py-3 text-sm shadow-sm">
                <div className="font-semibold text-black">Submitted by</div>
                <div className="mt-1.5 grid gap-0.5 text-[var(--anchor-gray)]">
                  {profileName    && <div><span className="font-medium text-black">{profileName}</span></div>}
                  {profileCompany && <div>{profileCompany}</div>}
                  {profilePhone   && <div>{profilePhone}</div>}
                  {profileEmail   && <div>{profileEmail}</div>}
                </div>
                <div className="mt-2 text-[11px] text-black/40">
                  Your contact information is pulled from your account. Update it in your profile settings.
                </div>
              </div>
            )}

            {display.map((item) =>
              item.type === "ai" ? (
                <div
                  key={item.id}
                  className="rounded-2xl border border-black/10 bg-white px-4 py-3 text-sm leading-relaxed shadow-sm text-black whitespace-pre-wrap"
                >
                  {item.text}
                </div>
              ) : (
                <div key={item.id} className="flex justify-end">
                  <div
                    className="rounded-2xl border px-4 py-2 text-sm font-semibold shadow-sm"
                    style={{
                      backgroundColor: "#F0FDF4",
                      borderColor: "rgba(4,120,53,0.25)",
                      color: "#047835",
                    }}
                  >
                    {item.text}
                  </div>
                </div>
              )
            )}

            {/* Loading indicator */}
            {loading && (
              <div className="rounded-2xl border border-black/10 bg-white px-4 py-3 text-sm text-black/50 shadow-sm flex items-center gap-2">
                <span
                  style={{
                    display: "inline-block",
                    width: 12,
                    height: 12,
                    border: "2px solid rgba(4,120,53,0.2)",
                    borderTopColor: "#047835",
                    borderRadius: "50%",
                    animation: "spin 0.7s linear infinite",
                    flexShrink: 0,
                  }}
                />
                Thinking…
              </div>
            )}

            {/* PDF status */}
            {assessment.isComplete && !loading && (
              <div className="rounded-2xl border px-4 py-3 text-sm shadow-sm"
                style={{ borderColor: "#BBF7D0", backgroundColor: "#F0FDF4" }}>
                {pdfGenerating && (
                  <div className="flex items-center gap-2 font-semibold" style={{ color: "#047835" }}>
                    <span style={{
                      display: "inline-block", width: 14, height: 14,
                      border: "2px solid rgba(4,120,53,0.25)", borderTopColor: "#047835",
                      borderRadius: "50%", animation: "spin 0.7s linear infinite", flexShrink: 0,
                    }} />
                    Generating your report…
                  </div>
                )}
                {pdfBlob && !pdfGenerating && (
                  <div className="flex flex-col gap-2">
                    <div className="font-semibold" style={{ color: "#047835" }}>Report downloaded successfully.</div>
                    <button
                      type="button"
                      onClick={() => triggerBlobDownload(pdfBlob, assessment)}
                      className="self-start rounded-lg px-4 py-2 text-xs font-semibold text-white transition"
                      style={{ backgroundColor: "#047835" }}
                    >
                      Download again
                    </button>
                  </div>
                )}
                {pdfError && !pdfGenerating && (
                  <div className="text-red-700">{pdfError}</div>
                )}
              </div>
            )}

            <div ref={scrollRef} />
          </div>

          {/* ── Option buttons ─────────────────────────────────────────────── */}
          {!assessment.isComplete && options.length > 0 && !loading && (
            <div className="shrink-0 pt-3 pb-[calc(0.75rem+env(safe-area-inset-bottom))]">
              <div className="flex flex-col items-center gap-2 sm:flex-row sm:flex-wrap sm:justify-center">
                {options.map((opt) => (
                  <button
                    key={opt}
                    type="button"
                    onClick={() => handleSelect(opt)}
                    className="w-full rounded-xl border px-5 py-3 text-sm font-semibold transition-colors duration-150 active:scale-[0.98] sm:w-auto"
                    style={{
                      borderColor: "#047835",
                      color: "#047835",
                      backgroundColor: "white",
                      minHeight: 44,
                    }}
                    onMouseEnter={(e) => {
                      (e.currentTarget as HTMLButtonElement).style.backgroundColor = "#047835";
                      (e.currentTarget as HTMLButtonElement).style.color = "white";
                    }}
                    onMouseLeave={(e) => {
                      (e.currentTarget as HTMLButtonElement).style.backgroundColor = "white";
                      (e.currentTarget as HTMLButtonElement).style.color = "#047835";
                    }}
                  >
                    {opt}
                  </button>
                ))}
              </div>
            </div>
          )}

          {assessment.isComplete && !loading && (
            <div className="shrink-0 border-t border-black/10 pt-3 pb-[calc(0.75rem+env(safe-area-inset-bottom))]">
              <Link href="/dashboard">
                <Button variant="primary" className="w-full sm:w-auto">Back to Dashboard</Button>
              </Link>
            </div>
          )}
        </div>
      </div>
    </main>
  );
}
