#!/usr/bin/env python3
"""
Read scripts/manufacturer_contacts.json and emit a Supabase migration that
upserts every contact into public.manufacturer_contacts.

Usage:
  python3 scripts/generate_manufacturer_contacts_seed.py > supabase/migrations/20260519_000021_seed_manufacturer_contacts.sql
"""
import json
import sys
from pathlib import Path


def q(s):
    """SQL-quote a string, escaping single quotes."""
    if s is None or s == "":
        return "null"
    return "'" + str(s).replace("'", "''") + "'"


def qjson(d):
    return q(json.dumps(d or {}, ensure_ascii=False))


def main():
    p = Path(__file__).resolve().parent / "manufacturer_contacts.json"
    rows = json.loads(p.read_text())
    print("-- Auto-generated by scripts/generate_manufacturer_contacts_seed.py")
    print("-- Source: Manufacturer Rep Lists 202508.xlsx")
    print(f"-- {len(rows)} contacts; do not edit by hand.")
    print()
    print("begin;")
    print()

    # Two passes:
    # 1) rows with email — upsert on (manufacturer, lower(email)) so reruns
    #    are idempotent.
    # 2) rows without email — straight insert (the unique index excludes them).
    with_email = [r for r in rows if r.get("email")]
    without_email = [r for r in rows if not r.get("email")]

    if with_email:
        print(f"-- {len(with_email)} contacts with email")
        print("insert into public.manufacturer_contacts")
        print("  (manufacturer, first_name, last_name, full_name, email, phone, cell, title, territory, region, raw)")
        print("values")
        for i, r in enumerate(with_email):
            cols = [
                q(r["manufacturer"]),
                q(r.get("first_name")),
                q(r.get("last_name")),
                q(r.get("full_name")),
                q(r["email"]),
                q(r.get("phone")),
                q(r.get("cell")),
                q(r.get("title")),
                q(r.get("territory")),
                q(r.get("region")),
                qjson(r.get("raw")),
            ]
            sep = "," if i < len(with_email) - 1 else ""
            print("  (" + ", ".join(cols) + ")" + sep)
        print("on conflict (manufacturer, lower(email)) where email is not null do update set")
        print("  first_name = excluded.first_name,")
        print("  last_name  = excluded.last_name,")
        print("  full_name  = excluded.full_name,")
        print("  phone      = excluded.phone,")
        print("  cell       = excluded.cell,")
        print("  title      = excluded.title,")
        print("  territory  = excluded.territory,")
        print("  region     = excluded.region,")
        print("  raw        = excluded.raw,")
        print("  updated_at = now();")
        print()

    # Wipe email-less rows from a prior run and reinsert. They have no unique
    # key, so the only safe way to keep the seed idempotent is delete-then-insert.
    if without_email:
        # Delete any prior emailless rows for the manufacturers we're about
        # to re-seed, scoped to first/last we're inserting so we don't nuke
        # rows added manually.
        names = sorted({(r["manufacturer"], r.get("first_name") or "", r.get("last_name") or "") for r in without_email})
        print(f"-- {len(without_email)} contacts without email (delete-and-insert)")
        for m, f, l in names:
            print(
                "delete from public.manufacturer_contacts "
                f"where email is null and manufacturer = {q(m)} "
                f"and coalesce(first_name,'') = {q(f)} and coalesce(last_name,'') = {q(l)};"
            )
        print()
        print("insert into public.manufacturer_contacts")
        print("  (manufacturer, first_name, last_name, full_name, email, phone, cell, title, territory, region, raw)")
        print("values")
        for i, r in enumerate(without_email):
            cols = [
                q(r["manufacturer"]),
                q(r.get("first_name")),
                q(r.get("last_name")),
                q(r.get("full_name")),
                "null",
                q(r.get("phone")),
                q(r.get("cell")),
                q(r.get("title")),
                q(r.get("territory")),
                q(r.get("region")),
                qjson(r.get("raw")),
            ]
            sep = "," if i < len(without_email) - 1 else ""
            print("  (" + ", ".join(cols) + ")" + sep)
        print(";")
        print()

    print("commit;")


if __name__ == "__main__":
    main()
